<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
py_casters=['Eyjafjalla', 'Goldenglow', 'Ceobe'] # Python list
py_medics=['Shining', 'Nightingale', 'Kal\'tsit']

In [4]:
np_casters=np.array(['Eyjafjalla', 'Goldenglow', 'Ceobe']) # NumPy arrays
np_medics=np.array(['Shining', 'Nightingale', 'Kal\'tsit'])

In [3]:
operator_info= { # Dictionary
    'Eyjafjalla' : 'Caster',
    'Kal\'tsit' : 'Medic',
    'Archetto' : 'Sniper'
}

dictionaries store data in the structure  
`key : value,`  
`key : value`  

order matters for lists and arrays

organising data affects how one thinks about it

## 1.2 Accessing data from a list (or array)

In [7]:
py_casters[0]

'Eyjafjalla'

In [8]:
py_casters[2]

'Ceobe'

In [16]:
x=1 # assigning variable to pull position-matched entries from both lists
print(f"{py_casters[x]} is paired with {py_medics[x]}")

Goldenglow is paired with Nightingale


In [17]:
py_casters[-1] # negative indexing

'Ceobe'

Python is **zero-indexed**, meaning lists and arrays are stored starting from position 0 from left to right  
variable can be assigned to match a position in the index  
negative numbers (reverse indexing) can be used to pull data from the last entry (assigned position -1)

## 1.3 Accessing data from a dictionary

In [15]:
operator_info["Eyjafjalla"] # only keys can be used to get the value, not the other way around

'Caster'

In [4]:
operator_info.keys()

dict_keys(['Eyjafjalla', "Kal'tsit", 'Archetto'])

In [5]:
operator_info.values()

dict_values(['Caster', 'Medic', 'Sniper'])

note that dictionaries have a `key : value` structure  
the data (value) can be accessed using the key, but not vice versa  
`.keys()` obtains all keys from the dictionary  
`.values()` obtains all data from the dictionary

## 1.4 Higher dimensional lists

In [18]:
py_operator_list=[["Eyja","Medic"],
                  ["Swire","Specialist"],
                  ["Mountain","Guard"]
                 ]

2D lists can be thought of as a "list of lists"  
2D arrays are also possible

# 2 Lists vs. Arrays

## 2.1 Size

In [19]:
len(py_operator_list)

3

In [20]:
np_array_oplist=np.array(py_operator_list)

In [22]:
len(np_array_oplist)

3

In [23]:
np_array_oplist.shape

(3, 2)

`len()` gives the number of entries in a given list or array -- can be useful for accessing data

an array has the property `.shape` that describes the number of distinct values in each entry

## 2.2 Arrays are fussy about type

In [25]:
py_numlist=['X', 'Y', 2]
print(py_numlist)

['X', 'Y', 2]


In [26]:
np_numlist=np.array(['X','Y',2])
print(np_numlist)

['X' 'Y' '2']


numpy arrays can only hold a single type of data, while Python lists can hold a combination of data types  
arrays will look for the type that can encapsulate all the data inside (in this case, strings)

## 2.3 Adding a number

In [28]:
np_numlist=np.array([1,2,3,4,5])
np_numlist + 10

array([11, 12, 13, 14, 15])

In [6]:
py_list = [1,2,3,4,5]
py_list + 10

TypeError: can only concatenate list (not "int") to list

10 can be added to every number on the array  
`+` for Python lists is read as an effort to concatenate (combine) 2 lists together  
since the data type of 10 (int) was not a list, an error occurs

## 2.4 Adding another list

In [8]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list1+list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
array1=np.array(list1) # conversion of list to array
array2=np.array(list2)
array1+array2

array([ 7,  9, 11, 13, 15])

adding 2 lists produces a longer list (concatenation)  
adding 2 arrays adds each entry to its corresponding position together (better for math)

## 2.5 Multiplying by a Number

In [10]:
list1=[1,2,3,4,5]
list1*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
array1=np.array(list1)
array1*A

NameError: name 'A' is not defined

multiplying a list concatenates it with an identical copy (treated as `list1 + list1`)  
multiplying an array multiplies all its entries by the provided value (int/float)  
(note: cannot multiply an array by a letter to add the letter to each entry)

## 2.6 Squaring

In [19]:
array2=np.array([2,4,6,8,10])
array1*array2

array([ 2,  8, 18, 32, 50])

multiplying a list by a list (i.e. squaring it) does not work (multiplying lists is not an accepted operation)  
squaring an array squares all its entries (interpreted as `array1*array1`)  
confirmed the above by multiplying 2 different arrays, resulting in an array with each entry multiplied by its corresponding position in the other array

## 2.7 Asking questions

In [26]:
list1==5

False

In [27]:
array1==3

array([False, False,  True, False, False])

In [29]:
array1>=3

array([False, False,  True,  True,  True])

In [30]:
sum(array1>=3)

3

does not work for lists (or works in confusing ways)  
asking questions to an array applies the question to all its entries, and gives a corresponding true/false output  
`sum()` can also give the number of entries in an array that passes the test (by leveraging false = 0 and true = 1)

## 2.8 Mathematics

In [40]:
list1=[1,2,3,4,5]
print(sum(list1),
max(list1),
min(list1))

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [42]:
array2=np.array([2,4,6,8,10])
print(array2.sum(),
array2.max(),
array2.min())

print(array2.mean(), array2.std())

30 10 2
6.0 2.8284271247461903


functions like `sum()` only work in lists (and arrays) if all entries are the correct data type (int/float in this case)  
arrays work with hidden functions:  
`.sum()` -- alternatively general Python `sum()` can be used, but the Numpy hidden function is *faster*  
`.max()` -- `max()` in Python (lists cannot use the hidden array functions)  
`.min()` -- `min()` in Python  
arrays can also do `.mean()` and `.std()` for mean and standard deviation respectively

generally,  
lists: operations work on the list as a single entity  
arrays: operations work on each individual entry in the array

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes